### ISSUE TITLE
腾讯视频的签到链接在私信里无法打开

### ISSUE THREAD

**Issue by RoseannePark1** [BlueskyClouds/My-Actions#102]
显示unauthorized

**Comment by BlueskyClouds** [comment]
app登录没 不应该显示这个

**Comment by BlueskyClouds** [comment]
https://cdn.jsdelivr.net/gh/BlueskyClouds/BlueskyClouds.github.io@master/2021/01/15/img/v_2sign.jpg

**Comment by RoseannePark1** [comment]
就是按这个操作来的，之前成功过，但现在不行了

**Comment by BlueskyClouds** [comment]
那不清楚。。
