### ISSUE TITLE
通过reposync方式进行代码同步后的问题

### ISSUE THREAD

**Issue by leicancun** [BlueskyClouds/My-Actions#105]
大佬你好,我按照[reposync.md](https://github.com/BlueskyClouds/My-Actions/blob/master/reposync.md)中的教程进行了操作,发现的确是同步成功了,但是后续的动作无法触发,点Star也仅能触发刚刚的同步动作,后来我尝试将默认分支从main改为master后才触发了全部的动作,而之前用位于main分支中的同步动作已无法触发,是否只能触发默认分支中的动作?

**Comment by BlueskyClouds** [comment]
修改默认分支为master 
![Uploading QQ截图20210306143405.jpg…]()

**Comment by BlueskyClouds** [comment]
修改默认分支为master
![QQ截图20210306143405](https://user-images.githubusercontent.com/39831773/110197824-1a317400-7e89-11eb-97d4-3073f3d9a47c.jpg)

**Comment by leicancun** [comment]
所以只能触发默认分支中的动作对吗😂因为有好几个打卡的项目,我想如果放在分支能能触发我就可以把它们合并一下了

**Comment by BlueskyClouds** [comment]
你可以手动改，只不过自带同步会覆盖掉
