### ISSUE TITLE
腾讯只签到吗   弹幕那几个不完成？

### ISSUE THREAD

**Issue by wj420521** [BlueskyClouds/My-Actions#108]
证成功，执行主程序
腾讯视频会员二次签到：签到失败，自行在腾讯视频APP内登录网址签到http://v.qq.com/x/bu/mobile_checkin (基本每周都需要手动签到一次才可以.)
腾讯视频会员二次签到相关教程：https://cdn.jsdelivr.net/gh/BlueskyClouds/BlueskyClouds.github.io@master/202***/0***/***5/img/v_2sign.jpg
腾讯视频会员下载任务签到： QZOutputJson=({"msg":"任务未完成","ret":-777902});
腾讯视频会员手机端签到失败：重复签到 ‼️‼️
腾讯视频会员观看任务签到： QZOutputJson=({"msg":"任务未完成","ret":-777902});
腾讯视频会员赠送任务签到： QZOutputJson=({"msg":"任务未完成","ret":-777902});
腾讯视频会员弹幕任务签到： QZOutputJson=({"msg":"任务未完成","ret":-777902});

**Comment by BlueskyClouds** [comment]
手动完成的任务 并非自动完成
