### ISSUE TITLE
pushuplus推送

### ISSUE THREAD

**Issue by qq1270735037** [BlueskyClouds/My-Actions#114]
pushplus.hxtrip.com 已经发了相关通知，4月份前后即将关闭 pushplus.hxtrip.com 接口的推送
文章链接： https://mp.weixin.qq.com/s/XbWih4Mv5ggBPGg0-QBJJw

建议将 pushplus.hxtrip.com 域名改为 www.pushplus.plus 以便后续能继续使用推送加的服务

**Comment by BlueskyClouds** [comment]
3-20后更新
