### ISSUE TITLE
WPS 签到报错

### ISSUE THREAD

**Issue by jing207** [BlueskyClouds/My-Actions#125]
---wps网页签到---↓

签到失败信息: {"result":"error","data":"","msg":"\u672a\u9886\u53d6\u4efb\u52a1"}

任务1 “加入WPS大家庭”未完成,手动完成可获得wps会员3天 

任务2 “完善账户信息”未完成,手动完成可获得wps会员1天 

任务4 “连续签到两天”领取情况: 请先完成第一个任务

任务5 “WPS知识知多少”领取情况: 请先完成第一个任务

任务6 “初识WPS特色应用”领取情况: 请先完成第一个任务

任务8 “熟悉WPS会员特权”领取情况: 请先完成第一个任务

任务9 “文档输出为图片”领取情况: 请先完成第一个任务

任务12 “完成PDF转Word”领取情况: 请先完成第一个任务

任务16 “体验云文档功能”领取情况: 请先完成第一个任务

任务17 “完成图片转文字”领取情况: 请先完成第一个任务

任务23 “图片转PDF文档”领取情况: 请先完成第一个任务

已领取积分: 0

已领取会员: 0天

已完成任务: 0项

          ---稻壳网页签到---↓

签到信息: {"result":"ok","data":""}

本期连续签到: 1天

拥有补签卡: 0张

          ---wps小程序签到---↓

签到失败信息: {"result":"error","data":[],"msg":"ParamData Empty"}

签到接口失效, 请手动打卡

小程序打卡中累计获得会员: 11天

          ---当前用户信息---↓

会员积分:477

"稻米数量":0

会员信息:

"类型":WPS会员, "过期时间":2021--04--01 07:28:58

"类型":稻壳会员, "过期时间":2021--04--02 10:32:20

          ==========wps邀请==========

---为邀请---↓

邀请对象ID=01, Result: error

邀请对象ID=02, Result: error

邀请对象ID=03, Result: ok

邀请对象ID=04, Result: ok

邀请对象ID=05, Result: ok

邀请对象ID=06, Result: ok

邀请对象ID=07, Result: ID已失效

邀请对象ID=08, Result: ok

邀请对象ID=09, Result: ok

邀请对象ID=10, Result: ok

邀请对象ID=11, Result: ok

**Comment by BlueskyClouds** [comment]
签到无所谓，邀请正常就行，脚本签到不会获得积分。
