### ISSUE TITLE
哔哩哔哩漫画无法签到，报错代码如下

### ISSUE THREAD

**Issue by zerokos** [BlueskyClouds/My-Actions#13]
Run python3 function/bilibili_manga.py
/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host 'manga.bilibili.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host 'manga.bilibili.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
[2020-10-28 16:44:02][***] 服务繁忙, 尝试使用V3接口登录
[2020-10-28 16:44:02][***] 登录失败 {'ts': 1603903442, 'code': 0, 'data': {'status': 1, 'url': 'https://passport.bilibili.com/mobile/verifytel_h5.html?mid=*****9&tel=**********5&email=a***@1**.com&source=2&keepTime=0&appId=1149&subId=1&ticket=1'}}
哔哩哔哩漫画开始签到 start>>>
哔哩哔哩漫画获取签到信息 start>>>
累计签到0天🐶
哔哩哔哩银瓜子兑换硬币 start>>>
[2020-10-28 16:44:09][***] 银瓜子兑换硬币(APP通道)失败 {'code': 401, 'msg': '请登录', 'message': '请登录', 'data': []}
None

**Comment by BlueskyClouds** [comment]
需要验证码才能登录。

**Comment by zerokos** [comment]
> 需要验证码才能登录。

那是不是无法用了，有没有自动填写验证码的方法？

**Comment by BlueskyClouds** [comment]
暂无，你这是账号被风控了。可尝试更换密码在尝试，如果还不行就无解。

**Comment by BlueskyClouds** [comment]
查看你是否开启了登录设备管理，如开启 请关闭。

**Comment by zerokos** [comment]
> 暂无，你这是账号被风控了。可尝试更换密码在尝试，如果还不行就无解。

改了密码就好了，谢谢大佬
