### ISSUE TITLE
新版爱奇艺签到是不是有问题了

### ISSUE THREAD

**Issue by kayloving** [BlueSkyClouds/My-Actions#135]
我已经两天没有成功了

**Comment by BlueSkyClouds** [comment]
...没有过多修改，更换cookies试试

**Comment by BlueSkyClouds** [comment]
而且我看log你vip是不是已经到期了==

**Comment by kayloving** [comment]
> 而且我看log你vip是不是已经到期了==

并没有啊大佬，到明年过期

**Comment by BlueSkyClouds** [comment]
电脑端退出登录一次再重新登录 换一次cookie试试，无法解析json具体原因不明。

**Comment by yushangcl** [comment]
我也遇到这个问题了

**Comment by BlueSkyClouds** [comment]
排查中  待定

**Comment by BlueSkyClouds** [comment]
但签到貌似是正常的 可以签到 只是没抽奖和输出？

**Comment by kayloving** [comment]
> 但签到貌似是正常的可以签到只是没抽奖和输出？

是的，现在显示cookie无效，不过好像签到未断签，不过抽奖没了

**Comment by luckydzj** [comment]
我也碰到签到失败的问题了，我看了一下cookie，好像比以前多了点东西  &agenttype 前面多了些东西，不知道是不是这个原因导致的

**Comment by wzwcc** [comment]
我也是啊 失效了 我刚抓的cookie

**Comment by zeropoint58** [comment]
几天都是这个问题了

**Comment by RideWindOne** [comment]
用P0001的值也无效，退出重登录再获取也不行。

**Comment by BlueSkyClouds** [comment]
本地签到是正常的，疑似github actions 服务器无法访问 或者被封了    签到是正常  就是提示和抽奖失效了

**Comment by BlueSkyClouds** [comment]
请同步最新的  犯了个低级错误
https://github.com/BlueSkyClouds/My-Actions/commit/7fa7ea09a130d07301426bb37e7be6fb8c229148#r49728606

**Comment by BlueSkyClouds** [comment]
已修复 close
