### ISSUE TITLE
小米运动刷步数求收录

### ISSUE THREAD

**Issue by mjyhj** [BlueSkyClouds/My-Actions#145]
https://github.com/Squaregentleman/mimotion

**Comment by BlueSkyClouds** [comment]
已加

**Comment by mjyhj** [comment]
> 已加

时间推荐改到晚上6点后，一般不会早上10点就刷到一定步数。
要是加入排行榜的，就显得很假

**Comment by BlueSkyClouds** [comment]
国际标准时间0 10  就是北京时间 18 00
