### ISSUE TITLE
有点不懂自动同步仓库需要做什么

### ISSUE THREAD

**Issue by jkluio78** [BlueSkyClouds/My-Actions#146]
疑问1
是在setting填写PAT这个secret就可以自动同步了吗？
疑问2
如果做了1并不能自动同步，那么是要按 https://github.com/BlueSkyClouds/My-Actions/blob/master/RepoSync.md 进行操作就能自动同步了吗？
疑问3
还是说我根本就理解错了，以上两个都不是自动同步，而是需要手动触发才能同步？真正的自动同步是使用pull插件？

**Comment by BlueSkyClouds** [comment]
两种同步方法而已，一个是利用pull插件同步 一个是利用actions 自动定时拉取更新，当然有pull 用pull更简单 就不需要设置pat了

**Comment by BlueSkyClouds** [comment]
哪些不想fork的就是用 actions来同步

**Comment by jkluio78** [comment]
明白了
