### ISSUE TITLE
请问Secrets在哪里设置

### ISSUE THREAD

**Issue by bby0** [BlueskyClouds/My-Actions#16]
请问这些在哪里设置的，
![image](https://user-images.githubusercontent.com/45168196/97675199-d63cf580-1ac9-11eb-9187-a466aa43259a.png)

**Comment by BlueskyClouds** [comment]
settings -> secrets -> new secrets 详情查看视频教程，只不过自己新增就行

**Comment by bby0** [comment]
好的，多谢

**Comment by BlueskyClouds** [comment]
所有东西尽量都放在secrets 里 可以防止泄露   执行时间是国际标准时间 并非 中国时间 自行注意。

**Comment by bby0** [comment]
嗯嗯
