### ISSUE TITLE
腾讯视频刚添加进去就无法签到

### ISSUE THREAD

**Issue by cikichen** [BlueskyClouds/My-Actions#19]
`  node function/v_video.js
  shell: /bin/bash -e {0}
  env:
    V_REF_URL: ***
    V_COOKIE: ***
    SEND_KEY: 
    PUSH_KEY: 
    BARK_PUSH: 
    TG_BOT_TOKEN: ***
    TG_USER_ID: ***
    BARK_SOUND: 

🔔undefined, 开始!
验证成功，执行主程序
腾讯视频会员签到  签到失败, Cookie失效 ‼️‼️
`

Request URL: https://access.video.qq.com/user/auth_refresh?vappid=xxx&vsecret=xxx&type=wx&g_tk=&g_vstk=xx&g_actk=xx&callback=jQuery191032821775072734183_1604198862459&_=xxx

cookie: pgv_pvi=; pgv_si=; RK=; ptcz=4xxxxxxt_refresh_time=5404; login_time_last=2020-11-1 10:47:35

**Comment by BlueskyClouds** [comment]
我的一切正常，建议再抓一次尝试。 cookie 复制全 他会自动拆分以及更新。

**Comment by BlueskyClouds** [comment]
V_REF_URL = https://*****
V_COOKIE = pgv*****************

**Comment by BlueskyClouds** [comment]
请同步最新提交，已适配微信登录。
