### ISSUE TITLE
钉钉推送我写了个,实测可用,加在sendNotify.py就行

### ISSUE THREAD

**Issue by lancer-wang** [BlueskyClouds/My-Actions#31]
`    def dingNotify(self, text, desp):
        if sendNotify.DD_BOT_TOKEN != '':
            url = 'https://oapi.dingtalk.com/robot/send?access_token='+sendNotify.DD_BOT_TOKEN
            data = {
                "msgtype": "text",
                "text": {
                    'content': text+desp
                }
            }
            headers = {
                'Content-Type': 'application/json;charset=utf-8'
            }
            response = requests.post(url=url, data=json.dumps(data), headers=headers).text
            if json.loads(response)['errcode'] == 0:
                print('\n钉钉发送通知消息成功\n')
            else:
                print('\n发送通知失败！！\n')
        else:
            print('\n您未提供钉钉的有关数据，取消钉钉推送消息通知\n')
            pass`

**Comment by lancer-wang** [comment]
def dingNotify(self, text, desp):
        if sendNotify.DD_BOT_TOKEN != '':
            url = 'https://oapi.dingtalk.com/robot/send?access_token='+sendNotify.DD_BOT_TOKEN
            data = {
                "msgtype": "text",
                "text": {
                    'content': text+desp
                }
            }
            headers = {
                'Content-Type': 'application/json;charset=utf-8'
            }
            response = requests.post(url=url, data=json.dumps(data), headers=headers).text
            if json.loads(response)['errcode'] == 0:
                print('\n钉钉发送通知消息成功\n')
            else:
                print('\n发送通知失败！！\n')
        else:
            print('\n您未提供钉钉的有关数据，取消钉钉推送消息通知\n')
            pass

**Comment by BlueskyClouds** [comment]
已合并 可否更新测试下，我没环境。

**Comment by BlueskyClouds** [comment]
暂时close

**Comment by lancer-wang** [comment]
> 已合并 可否更新测试下，我没环境。
![image](https://user-images.githubusercontent.com/69783837/100400105-3d7da380-3090-11eb-9ddd-f0d3d8c53ace.png)
我很奇怪为什么获取不到DD_BOT_TOKEN,我在secret明明有添加

**Comment by lancer-wang** [comment]
> > 已合并 可否更新测试下，我没环境。
> > ![image](https://user-images.githubusercontent.com/69783837/100400105-3d7da380-3090-11eb-9ddd-f0d3d8c53ace.png)
> > 我很奇怪为什么获取不到DD_BOT_TOKEN,我在secret明明有添加

重新fork之后可以了,
