### ISSUE TITLE
v2ex的cookie该如何填

### ISSUE THREAD

**Issue by zerokos** [BlueskyClouds/My-Actions#32]
🔔V2ex自动签到, 开始!
获取成功 once:79118
获取成功 once:97562
20201120 的每日登录奖励 11 铜币
11/27/2020, 10:17:42 PM
签到失败
签到失败
20201120 的每日登录奖励 11 铜币

日志如上，11月20日是手动签到成功的，我把cookies全部复制填入，可以识别账号但签到没成功过

**Comment by BlueskyClouds** [comment]
就是官网的cookie 全部复制即可。
![QQ截图20201128175052](https://user-images.githubusercontent.com/39831773/100499162-4d85a800-31a2-11eb-96b5-c186e0bfc200.jpg)

**Comment by zerokos** [comment]
> 就是官网的cookie 全部复制即可。
> ![QQ截图20201128175052](https://user-images.githubusercontent.com/39831773/100499162-4d85a800-31a2-11eb-96b5-c186e0bfc200.jpg)

大大，我就是一样全部复制了，签到不成功是什么原因呢？

**Comment by BlueskyClouds** [comment]
重新复制一次试试，
