### ISSUE TITLE
腾讯视频，赠送、下载、弹幕任务都手动做了，定时任务不能一次性领取

### ISSUE THREAD

**Issue by thisPunk** [BlueskyClouds/My-Actions#33]
赠送、下载、弹幕任务都手动做了，定时任务是晚上22：00，不能一次性把这几个手动任务一起领取成长值，报错信息：
🔔腾讯视频会员签到, 开始!
验证成功，执行主程序
腾讯视频会员签到  以下任务仅领取,需要手动完成,如没有完成请无视
腾讯视频会员签到  12月13日, 签到失败，重复签到 ‼️‼️
腾讯视频会员观看任务签到  签到失败, 请勿重复领取任务 ‼️‼️
腾讯视频会员弹幕任务签到  签到失败, 请勿重复领取任务 ‼️‼️
腾讯视频会员赠送任务签到  QZOutputJson=({"msg":"未知错误","ret":-11023});
腾讯视频会员下载任务签到  签到成功，签到分数：10分 🎉

我肯定是都手动完成了的，现在解决方案就是多定几个定时任务，*/10 22 * * *，22点每10分钟执行一次，大佬有解决方案吗

**Comment by BlueskyClouds** [comment]
同步下最新的试试，

**Comment by BlueskyClouds** [comment]
可能是不能同时提交，具体原因我排查几天。 没这么多测试号

**Comment by thisPunk** [comment]
我把cookie发你了，手动任务已经完成，你如果方便测试可以测试一下。谢谢啦

**Comment by thisPunk** [comment]
qq邮箱查收

**Comment by BlueskyClouds** [comment]
OK 同步下最新的 已修复
![QQ截图20201214153224](https://user-images.githubusercontent.com/39831773/102052792-9afc4900-3e21-11eb-8d5a-4fdfa209bf88.jpg)

https://github.com/BlueskyClouds/My-Actions/commit/3ac309dd5488ad3fa3be3073b5e3a7d5816a6446

**Comment by thisPunk** [comment]
收到！谢谢

**Comment by BlueskyClouds** [comment]
对了如果你改过其中文件  自动同步是没办法同步的   还有问题留言或者重开issues即可
