### ISSUE TITLE
昨天改完百度崩溃了，看了几个fork的都是同样问题

### ISSUE THREAD

**Issue by thisPunk** [BlueskyClouds/My-Actions#34]
反复试了几次抓BUDSS，都是同样的报错，后看了几个用户的actions日志，都是同样的报错
![image](https://user-images.githubusercontent.com/73330662/102173050-271b7880-3ed5-11eb-8d91-52ec9f01b7f0.png)

**Comment by BlueskyClouds** [comment]
我看了你的log 你就没填写百度cookie的值啊。

**Comment by BlueskyClouds** [comment]
你点Run node function/tieba.js    里面百度 BUDSS   值都是空的。

**Comment by thisPunk** [comment]
解决了，把Secrets里删除重新添加就好了；之前也添加值了，怀疑是复制BDUSS这个名字时候带了空格什么的，多谢！
