### ISSUE TITLE
访问量

### ISSUE THREAD

**Issue by behappy00** [BlueskyClouds/My-Actions#35]
关注点可能有些奇怪，想知道最后的访问量怎末实现的？

**Comment by BlueskyClouds** [comment]
就默认打开就会访问一次=_=   [Visitor Count](https://profile-counter.glitch.me/你的名字/count.svg

**Comment by BlueskyClouds** [comment]
这种访问一次就+1  最简单的=_=  当然也可以刷 没必要。   而且fork后的访问自己的也+1

**Comment by behappy00** [comment]
谢谢，了解了
