### ISSUE TITLE
提示爱奇艺中奖接口异常

### ISSUE THREAD

**Issue by runishiwo** [BlueskyClouds/My-Actions#37]
爱奇艺-抽奖失败: 未知错误 ️ (1) response:

{"code":3,"errorReason":"中奖接口异常null","isTarget":0,"isSendGift":0}

爱奇艺-抽奖失败: 未知错误 ️ (2) response:

{"code":3,"errorReason":"中奖接口异常null","isTarget":0,"isSendGift":0}

爱奇艺-抽奖失败: 未知错误 ️ (3) response:

{"code":3,"errorReason":"中奖接口异常null","isTarget":0,"isSendGift":0}

**Comment by BlueskyClouds** [comment]
具体原因不清楚，并不是百分百出现，重复执行即可抽奖，可能是网络问题等。 有时间我看看。

**Comment by BlueskyClouds** [comment]
同步下最新的 ，增加输出排查原因.

**Comment by BlueskyClouds** [comment]
暂时多抽奖几次看看能不能解决，具体问题比较迷，实在不行直接每天签到抽奖两次。
