### ISSUE TITLE
腾讯视频二次签到接口加进去呗，应该可以吧

### ISSUE THREAD

**Issue by thisPunk** [BlueskyClouds/My-Actions#39]
二签链接：http://v.qq.com/x/bu/mobile_checkin
考虑一下，有时间研究研究哈
[
![微信图片_20201224154935](https://user-images.githubusercontent.com/73330662/103071986-baecf300-45ff-11eb-973b-327cc7683887.jpg)
](url)

**Comment by BlueskyClouds** [comment]
二签 我以为失效了就删了😂

**Comment by thisPunk** [comment]
一直有效，有时间搞一下

**Comment by BlueskyClouds** [comment]
我一直都是无匹配的签到活动..

**Comment by BlueskyClouds** [comment]
懂了，必须在app内私信打开一次。  而且7天一次

**Comment by thisPunk** [comment]
昂，是这样啊，我都是一帮发给某个联系人，然后找聊天记录或者评论记录去点击

**Comment by BlueskyClouds** [comment]
等我抓一份成功包再加，没测试号了233.
