### ISSUE TITLE
Fork 的新脚本报错

### ISSUE THREAD

**Issue by lonma** [BlueskyClouds/My-Actions#4]
大佬 这个提示算正常不？
npm WARN deprecated request@2.88.2: request has been deprecated, see request/request#3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm notice created a lockfile as package-lock.json. You should commit this file.
added 159 packages from 97 contributors and audited 159 packages in 5.147s
1 package is looking for funding
run npm fund for details

found 0 vulnerabilities

爱奇艺签到-爱奇艺-查询失败: 无到期数据 ⚠️
爱奇艺-签到失败: 今日已签到 ⚠️
爱奇艺-抽奖失败: 用户登录信息失效 ⚠️ (1)
爱奇艺-抽奖失败: 用户登录信息失效 ⚠️ (2)
爱奇艺-抽奖失败: 用户登录信息失效 ⚠️ (3)

**Comment by BlueskyClouds** [comment]
重新运行下试试
