### ISSUE TITLE
腾讯视频任务签到显示 no login是怎么回事啊，二次签到和手机端是成功的

### ISSUE THREAD

**Issue by mengdie101** [BlueskyClouds/My-Actions#50]
2021年01月11日

腾讯视频会员二次签到成功

腾讯视频会员手机端签到成功：签到分数：99分 

腾讯视频会员下载任务签到：no login

腾讯视频会员赠送任务签到：no login

腾讯视频会员弹幕任务签到：no login

腾讯视频会员观看任务签到：no login

**Comment by BlueskyClouds** [comment]
出现次数较低，重新执行一遍即可，并不是百分百出现。

**Comment by BlueskyClouds** [comment]
你是微信登录还是qq登录

**Comment by mengdie101** [comment]
微信登录的

**Comment by BlueskyClouds** [comment]
可能微信签到有问题，待定有时间排查一下。

**Comment by BlueskyClouds** [comment]
更换一次cookie和url 试试。

**Comment by BlueskyClouds** [comment]
每天都无法登陆吗？

**Comment by mengdie101** [comment]
是的，连续几天都是这个提示，重新运行也不行，这两天没法用电脑，等周末回去重新抓一次cookie试试

**Comment by BlueskyClouds** [comment]
已修复 同步最新的  多刷新一个参数应该就可以了。
