### ISSUE TITLE
哔哩哔哩漫画签到

### ISSUE THREAD

**Issue by BOOTV** [BlueskyClouds/My-Actions#53]
签到成功后报错:
`/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'manga.bilibili.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
[2021-01-13 07:51:23][***] 服务繁忙, 尝试使用V3接口登录
[2021-01-13 07:51:23][***] 登录成功
True
哔哩哔哩漫画开始签到 start>>>
今日已签到.
哔哩哔哩漫画获取签到信息 start>>>
累计签到1天🐶
哔哩哔哩银瓜子兑换硬币 start>>>
[2021-01-13 07:51:30][***] 银瓜子兑换硬币(APP通道)失败 {'code': 403, 'msg': '每天最多能兑换 1 个', 'message': '每天最多能兑换 1 个', 'data': []}
None

您未提供server酱的SCKEY，取消微信推送消息通知

您未提供Bark的APP推送BARK_PUSH，取消Bark推送消息通知

您未提供Bark的APP推送BARK_PUSH，取消Bark推送消息通知

  warnings.warn(
/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'manga.bilibili.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
Traceback (most recent call last):
  File "function/bilibili_manga.py", line 74, in <module>
    sendNotify.send(title = u"哔哩哔哩漫画签到",msg = msg)
  File "/home/runner/work/My-Actions/My-Actions/function/sendNotify.py", line 159, in send
    send.dingNotify(title,msg)
  File "/home/runner/work/My-Actions/My-Actions/function/sendNotify.py", line 135, in dingNotify
    timestamp = long(round(time.time() * 1000))
NameError: name 'long' is not defined
Error: Process completed with exit code 1.`

**Comment by BlueskyClouds** [comment]
同步最新的

**Comment by BOOTV** [comment]
最新的还是这样...

**Comment by BlueskyClouds** [comment]
更新后重新运行。并不是运行之前失败的。

**Comment by BlueskyClouds** [comment]
再同步一次.

**Comment by BOOTV** [comment]
已解决
