### ISSUE TITLE
腾讯视频签到问题，server酱https挂了

### ISSUE THREAD

**Issue by chengweng** [BlueskyClouds/My-Actions#55]
您好！作者大大，帮忙抽空看下腾讯视频中出现这个no login问题
![图片](https://user-images.githubusercontent.com/26996504/104669450-fb2e2580-5714-11eb-8d62-be45a88c2588.png)
还有server酱的https好像挂了，发送不了了
谢谢作者大大了，麻烦了

**Comment by nick814** [comment]
兄弟server酱和作者没关系 ，挂了过会会恢复的 用的人太多了

发件人: muweng <notifications@github.com>
发送时间: 2021年1月15日 9:37
收件人: BlueskyClouds/My-Actions <My-Actions@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [BlueskyClouds/My-Actions] 腾讯视频签到问题，server酱https挂了 (#55)


您好！作者大大，帮忙抽空看下腾讯视频中出现这个no login问题
[图片]<https://user-images.githubusercontent.com/26996504/104669450-fb2e2580-5714-11eb-8d62-be45a88c2588.png>
还有server酱的https好像挂了，发送不了了
谢谢作者大大了，麻烦了

**Comment by BlueskyClouds** [comment]
你是微信登录吗？
微信登录可能会无法领取任务提示未登录  已知，待修复  server酱可能是你被封了。

**Comment by chengweng** [comment]
1、server酱我早上用postman试了   他的https的ssl好像过期了   用http可以，刚才我重新试了下，他https恢复了
2、是的我是微信登录
@BlueskyClouds 谢谢大佬，因为我会员是用微信账户开的

**Comment by BlueskyClouds** [comment]
微信登录是有这个问题，待修复，很迷同一个cookie 能签到但是没办法领取任务😂

**Comment by chengweng** [comment]
我看了微信登录的cookie，他应该用了oauth授权，他里面有access_token和refresh_token属性,应该用的是微信小程序授权那套模式

**Comment by BlueskyClouds** [comment]
https://github.com/BlueskyClouds/My-Actions/commit/1e81f9dff424f5eebcdff9ca198b1974c0308572

同步最新的尝试，暂时close issues，如还不行留言即可。
