### ISSUE TITLE
wps的脚本怎么删掉了

### ISSUE THREAD

**Issue by leic4u** [BlueskyClouds/My-Actions#60]
正准备开始配置用起来，发现被删了。。。

**Comment by BlueskyClouds** [comment]
wps组团目前 每个账户只能邀请3次，而且只有邀请 就暂时下了 。脚本可以看记录手动加就行。

**Comment by leic4u** [comment]
> wps组团目前 每个账户只能邀请3次，而且只有邀请 就暂时下了 。脚本可以看记录手动加就行。

@BlueskyClouds 后面会考虑加上吗？

**Comment by leic4u** [comment]
另外请求一下加上多看的签到

**Comment by leic4u** [comment]
> wps组团目前 每个账户只能邀请3次，而且只有邀请 就暂时下了 。脚本可以看记录手动加就行。

手动加上试用了一下你删除的wps签到脚本，感觉已经很棒了。集结那部分只需要自己找几个小号，把内置的小号sid替换掉就行。

**Comment by leic4u** [comment]
@BlueskyClouds 我发现好像 @chavyleung 的脚本可以实现WPS的自动打卡，参见 [这个JS](https://github.com/xuxiaobo4510/APPSIGN/blob/master/wps.js)，[这个workflow](https://github.com/xuxiaobo4510/APPSIGN/blob/master/.github/workflows/wps.yml) 和 [这个build](https://github.com/xuxiaobo4510/APPSIGN/runs/1759147239?check_suite_focus=true) ，但是我Fork了一下 @xuxiaobo4510 的repo，配置了WPS_URL和WPS_COOKIE两个SECRET后，还是跑不起来，不知道是为啥，大佬可以参考看下。

**Comment by BlueskyClouds** [comment]
好的我有时间加

**Comment by BlueskyClouds** [comment]
他并没有微信打卡，直接注释掉了，只是签到，打卡还是得手动打卡。

**Comment by leic4u** [comment]
本来想测试一下，但是我用Loon获取WPS_URL和WPS_COOKIE死活获取不到，各种办法都试了没办法，弃坑。。。
