### ISSUE TITLE
腾讯视频签到失败

### ISSUE THREAD

**Issue by FairyWorld** [BlueskyClouds/My-Actions#61]
腾讯视频除了第一个签到外，从第二次签到开始就全部失败了。
我按照日志的提示私信别人，点击签到链接说找不到活动。后面的下载，观看，弹幕等任务失败原因未知
![image](https://user-images.githubusercontent.com/32956212/105665982-2aae1080-5f13-11eb-8ce9-74af8ef3df9c.png)

**Comment by BlueskyClouds** [comment]
任务只是手动领取 ，完成还是得手动完成，   二次签到 私信打开后会提示签到成功，然后每7天就需要手动打开一次链接，可以不用。

**Comment by FairyWorld** [comment]
> 任务只是手动领取 ，完成还是得手动完成， 二次签到 私信打开后会提示签到成功，然后每7天就需要手动打开一次链接，可以不用。
第二次签到在app私信点击链接匹配不了活动，是不是活动过期了
![image](https://user-images.githubusercontent.com/32956212/105667092-aad57580-5f15-11eb-800d-fe70f5c80a28.png)

**Comment by BlueskyClouds** [comment]
没有过期，我刚刚都打开了。 你是不是微信登录？

**Comment by FairyWorld** [comment]
> 没有过期，我刚刚都打开了。 你是不是微信登录？

我用的是qq

**Comment by BlueskyClouds** [comment]
那不清楚，我刚试过了，微信和QQ都可以，就算没有会员也可以签到

**Comment by BlueskyClouds** [comment]
http://v.qq.com/x/bu/mobile_checkin

**Comment by FairyWorld** [comment]
> 那不清楚，我刚试过了，微信和QQ都可以，就算没有会员也可以签到

我两个都不行，可能是我手机被检测出root了或者是一个替换webview的插件导致的，待会我再测一下

**Comment by BlueskyClouds** [comment]
那可能是webview导致的。😂

**Comment by FairyWorld** [comment]
> 那可能是webview导致的。😂

放弃了，还是不行

**Comment by BlueskyClouds** [comment]
暂时close
