### ISSUE TITLE
B站签到登录失败

### ISSUE THREAD

**Issue by hzys** [BlueskyClouds/My-Actions#62]
使用账号、密码 运行久了就出现这个问题了，然后我把验证手机号的完整链接通过tg机器人发送到了我手机上了，验证之后再次运行还是失败提示  'message': '您的账号存在高危异常行为，为了您的账号安全，请验证手机号后登录帐号' ，请问作者有啥办法解决不？

**Comment by hzys** [comment]
没看到，原来改密码就可以

**Comment by BlueskyClouds** [comment]
增加了cookie登陆，等一段时间不是异地登陆了就可以用账号密码了。

**Comment by hzys** [comment]
> 增加了cookie登陆，等一段时间不是异地登陆了就可以用账号密码了。
请问cookie里面填什么啊？只要bili_jct？

**Comment by BlueskyClouds** [comment]
官网全部即可，
