### ISSUE TITLE
WPS的wps_invitation.py运行失败

### ISSUE THREAD

**Issue by fuckpony** [BlueskyClouds/My-Actions#71]
这是什么问题?
![image](https://user-images.githubusercontent.com/52879142/106884399-391ed800-671c-11eb-8a9f-2f414609acf1.png)

**Comment by BlueskyClouds** [comment]
推送 自动替换换行问题 有时间我看看 不影响其他 只是推送而已。

**Comment by BlueskyClouds** [comment]
集结问题 已删除
