### ISSUE TITLE
爱奇艺

### ISSUE THREAD

**Issue by arukas-y** [BlueskyClouds/My-Actions#8]
现在爱奇艺PC端使用f12搜索不到authcookie了

**Comment by arukas-y** [comment]
![Uploading 2506C72A-E41F-42E3-B826-2CF38DB601BB.png…]()

**Comment by BlueskyClouds** [comment]
打开控制台后 按下F12 然后刷新一次后再搜索  F5， 刚测试过 能获取到，

**Comment by BlueskyClouds** [comment]
使用F12打开控制台后  再按F5 刷新一次后再搜索 ， 刚测试过 能获取到，

**Comment by arukas-y** [comment]
> 使用F12打开控制台后 再按F5 刷新一次后再搜索 ， 刚测试过 能获取到，
现在可以了。对比了下教程截图，发现f12控制台Network这里的一个叫Presever log的选项没有打开

**Comment by BlueskyClouds** [comment]
> > 使用F12打开控制台后再按F5刷新一次后再搜索，刚测试过能获取到，
> > 现在可以了。对比了下教程截图，发现f12控制台网络这里的一个叫Presever log的选项没有打开

好的，我好在相关教程的介绍添加此项，防止部分人不清楚.

**Comment by arukas-y** [comment]
请问telegram推送支持吗，

**Comment by BlueskyClouds** [comment]
已新增，自行测试是否存在问题，因为我不怎么用telegram

**Comment by arukas-y** [comment]
好的

**Comment by arukas-y** [comment]
已测试，telegram推送可用

**Comment by ouminling** [comment]
可以多个B站账号签到吗？怎么操作
