### ISSUE TITLE
腾讯视频二次签到和各种任务签到失败

### ISSUE THREAD

**Issue by ShenHai9** [BlueskyClouds/My-Actions#81]
`🔔腾讯视频会员签到, 开始!
验证成功，执行主程序
腾讯视频会员手机端签到失败：重复签到 ‼️‼️
腾讯视频会员二次签到：签到失败，请复制链接在app内私信发送后手动打开一次 http://v.qq.com/x/bu/mobile_checkin (基本每周都需要手动签到一次才可以.)
腾讯视频会员二次签到相关教程：https://cdn.jsdelivr.net/gh/BlueskyClouds/BlueskyClouds.github.io@master/2021/01/15/img/v_2sign.jpg
腾讯视频会员下载任务签到： QZOutputJson=({"msg":"任务未完成","ret":-777902});
腾讯视频会员赠送任务签到： QZOutputJson=({"msg":"任务未完成","ret":-777902});
腾讯视频会员弹幕任务签到： QZOutputJson=({"msg":"任务未完成","ret":-777902});
腾讯视频会员观看任务签到： QZOutputJson=({"msg":"任务未完成","ret":-777902});`

已经按照
`腾讯视频会员二次签到：签到失败，请复制链接在app内私信发送后手动打开一次 http://v.qq.com/x/bu/mobile_checkin (基本每周都需要手动签到一次才可以.)`
操作

但是二次签到和各种任务签到依旧失败。

请问是什么原因呢？

**Comment by BlueskyClouds** [comment]
任务需要手动完成，二次签到 可无视，因为经常失效需要手动去app里打开一次链接

**Comment by BlueskyClouds** [comment]
貌似二次签到提示有点问题，有时间看看

**Comment by ShenHai9** [comment]
啊这 原来任务是手动完成的 好的 大概了解了 感谢 很不错的项目
