### ISSUE TITLE
能否增加企业微信应用消息推送

### ISSUE THREAD

**Issue by vay1314** [BlueskyClouds/My-Actions#87]
辛苦维护，感谢。
能否增加企业微信应用消息推送，因为S酱新推送限额了，而且也是推送企业微信应用消息推送。
lxk0301的推送js例子，https://gitee.com/lxk0301/jd_scripts/blob/master/sendNotify.js
企业微信应用消息推送说明，https://note.youdao.com/ynoteshare1/index.html?id=351e08a72378206f9dd64d2281e9b83b&type=note
官方API：https://work.weixin.qq.com/api/doc/90000/90135/90250

**Comment by BlueskyClouds** [comment]
js版加了，py的还没加，

**Comment by vay1314** [comment]
> js版加了，py的还没加，

好的
