### ISSUE TITLE
WPS邀请现在只成功一两个人

### ISSUE THREAD

**Issue by qingyu0725** [BlueskyClouds/My-Actions#89]
大佬是没用这个完成任务吗？那个腾讯云函数上也是只能一两个，能修复下或者提供新方法吗？

**Comment by 1325266720** [comment]
确实是这样的，好像是wps更新了sid，求更新

**Comment by BlueskyClouds** [comment]
我没用这份，只不过前几天wps更新修复了我那个方法，晚点我去看看

**Comment by BlueskyClouds** [comment]
同步下 最新的再试试，wps加了规则 不能同时邀请，需要加个延迟即可。
