### ISSUE TITLE
请问大佬一下，放在git中运行会出现泄密吗？

### ISSUE THREAD

**Issue by ICEOOX** [BlueskyClouds/My-Actions#96]
### 感谢作者维护！

我之前看到很多人讲，放在git运行会导致cookie信息泄露，特意问一下
当然这里我并不是指你会泄露，我只是想**弄清楚**使用代码的安全风险，_好并做好其他措施_

**Comment by BlueskyClouds** [comment]
那是原作者失误导致，而且直接输出cookie是无法输出出来的，你可以新建个仓库试试

**Comment by ICEOOX** [comment]
放心了
