### ISSUE TITLE
腾讯视频的需要手动做任务？除签到外

### ISSUE THREAD

**Issue by insoxin** [BlueskyClouds/My-Actions#98]
比如发弹幕下载看剧一小时等等

`腾讯视频会员观看任务签到： QZOutputJson=({"msg":"任务未完成","ret":-777902});
35
您未提供push+推送所需的PUSH_PLUS_TOKEN，取消push+推送消息通知
37
`

**Comment by BlueskyClouds** [comment]
是的 需要手动完成
