### ISSUE TITLE
B站登陆失败了，如何获取到B站登陆所需的cookie

### ISSUE THREAD

**Issue by RoseannePark1** [BlueskyClouds/My-Actions#99]
是看cookie里的哪个参数

**Comment by BlueskyClouds** [comment]
全部

**Comment by BlueskyClouds** [comment]
全部复制粘贴进去即可。

**Comment by RoseannePark1** [comment]
![image](https://user-images.githubusercontent.com/76609897/109624665-7179d080-7b79-11eb-9a8c-b395b9dc5740.png)

**Comment by RoseannePark1** [comment]
![image](https://user-images.githubusercontent.com/76609897/109624741-86eefa80-7b79-11eb-91c7-7c3256b48802.png)
是这里的吗😂

**Comment by BlueskyClouds** [comment]
![QQ截图20210303015527](https://user-images.githubusercontent.com/39831773/109692510-95620400-7bc3-11eb-8e10-8f82cea36f8b.jpg)
cookie: 后面的全部复制粘贴即可

**Comment by LoveForeverBoa** [comment]
学习一下
